function init(self)
	points_count = 10
	local buf = buffer.create(points_count*2, {
		{ name = hash("position"), type=buffer.VALUE_TYPE_FLOAT32, count = 3 },
		{ name = hash("texcoord0"), type=buffer.VALUE_TYPE_FLOAT32, count = 2 },
		{ name = hash("tint"), type=buffer.VALUE_TYPE_FLOAT32, count = 7 },
	})
	local vertex_position_stream = buffer.get_stream(buf, "position")
	local vertex_texcoord_stream = buffer.get_stream(buf, "texcoord0")
	faststream.set_vector2_to_stream(vertex_texcoord_stream, 1, vmath.vector3(2, 3, 4))
	faststream.set_vector2_to_stream(vertex_texcoord_stream, 2, vmath.vector3(10, 11, 22))
	faststream.set_vector2_to_stream(vertex_texcoord_stream, 3, vmath.vector3(13, 14, 52))

	local t = {vmath.vector3(1,2,3), vmath.vector3(1,2,3), vmath.vector3(1,2,3), vmath.vector3(1,2,3)}
	
	faststream.set_table(vertex_position_stream, t)
	for i=1, #vertex_position_stream do
		print(vertex_position_stream[i])
	end
end